app/urls.py
from django.urls import path 

from .views import (start_page, logout_user, MainPageView,
                    ChangeReviewView)


urlpatterns = (
    path('', start_page, name="login"),
    path('main/', MainPageView.as_view(), name='main'),
    path('logout/', logout_user, name='logout'),
    path('change/<int:id>/', ChangeReviewView.as_view(), name="change")
)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .settings import (DEBUG, MEDIA_ROOT, MEDIA_URL, 
                       STATIC_URL, STATIC_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('app.urls'))
]
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)
if DEBUG: urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

User = get_user_model()


# Create your models here.
class UserImageModel(models.Model):
    """
    Model for storage users' image
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="image", verbose_name="Пользовтель")
    image = models.ImageField(upload_to="user_profiles/", verbose_name="Изображение")


class PlaceModel(models.Model):
    """
    Model for storage users' reviews about places
    """
    name = models.TextField(null=False, blank=False, max_length=60, verbose_name="Название места")
    description = models.TextField(null=False, blank=False, max_length=500, verbose_name="Описание")
    longitude = models.FloatField(null=False, blank=False, verbose_name="Широта")
    latitude = models.FloatField(null=False, blank=False, verbose_name="Долгота")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")

    def get_absolute_url(self):
        return reverse_lazy("change", kwargs={"id": self.pk})

app/forms.py
from django.core.exceptions import ValidationError
from django import forms

from .models import PlaceModel


class PlacesForm(forms.ModelForm):
    """
    Form for creating reviews
    """
    class Meta:
        model = PlaceModel
        coords = forms.NumberInput(attrs={'type': 'hidden'})
        fields = ("name", "description", "latitude", "longitude")

    def clean_name(self):
        """
        name's field validation
        """
        name = self.data["name"]
        if not name:
            raise ValidationError("name is blank")
        return name

    def clean_description(self):
        """
        description's field validation
        """
        desrc = self.data.get("description")
        if not desrc:
            raise ValidationError("description is blank")
        return desrc

    def clean_latitude(self):
        """
        latitude's field validation
        """
        lat = self.data.get("latitude")
        if not -180.0 <= float(lat) <= 180.0:
            raise ValidationError("Value is not in correct range")
        return lat

    def clean_longitude(self):
        """
        longitude's field validation
        """
        longitude = self.data.get("longitude")
        print(longitude)
        if not -90.0 <= float(longitude) <= 90.0:
            raise ValidationError("Value is not in correct range")
        return longitude

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.views.generic import ListView, FormView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

from .models import PlaceModel
from .mixin import DatamixIn
from .forms import PlacesForm

# Create your views here.


def start_page(request):
    """
    Application's entrypoint
    """
    return render(request, 'startpage.html')


class MainPageView(LoginRequiredMixin, DatamixIn, ListView, FormView):
    """
    Main page where there are the list of reviews and form for adding new reviews
    """
    template_name = 'main.html'
    model = PlaceModel
    context_object_name = "reviews"
    form_class = PlacesForm

    def get_queryset(self, *args, **kwargs):
        return PlaceModel.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context | self.get_data

    def form_valid(self, form):
        new_entry = form.save(commit=False)
        new_entry.user = self.request.user
        new_entry.save()
        return JsonResponse({"message": "Впечатление было успешно создано",
                            "status": 200}, status=200)

    def form_invalid(self, form):
        print(form.errors)
        return JsonResponse({"status": 400}, status=400)


class ChangeReviewView(LoginRequiredMixin, DatamixIn, View):
    """
        Page for review change
    """
    @property
    def get_context_data(self):
        context = {
            'data': PlaceModel.objects.get(pk=self.kwargs["id"]),
        }
        return context | self.get_data

    def get(self, request, id):
        if not PlaceModel.objects.filter(pk=id, user=self.request.user).exists():
            return redirect("main")
        return render(request, 'change.html', context=self.get_context_data)

    def post(self, request, id):
        form = PlacesForm(self.request.POST)
        if form.is_valid():
            entry = PlaceModel.objects.get(pk=id)
            entry.name = form.cleaned_data["name"]
            entry.description = form.cleaned_data["description"]
            entry.longitude = form.cleaned_data["longitude"]
            entry.latitude = form.cleaned_data["latitude"]
            entry.save()
            return JsonResponse({"message": "Изменение сохранено успешно",
                                "status": 200}, status=200)
        return JsonResponse({"status": 400}, status=400)


def logout_user(request):
    """
    View function for logout
    """
    logout(request)
    return redirect('login')

app/templates/base.html
{%load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css'%}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    </head>
    <body>
        <header class="container-fluid">
                <nav id="nav-header" class="d-flex justify-content-center">
                    {% if request.user.is_authenticated %}
                        <p class="title">Добро пожаловать в Places Remember, {{user.first_name}} {{user.last_name}}</p>
                        <img class="user-image" src="{{photo.image.url}}" alt="">
                        <span class="login-btn"><a href="{% url 'logout' %}">Выйти</a></span>
                    {% else %}
                        <p class="title">Добро пожаловать в Places Remember</p>
                        <span class="login-btn"><a href="{% url 'social:begin' 'vk-oauth2' %}">Войти</a></span>
                    {% endif %}
                </nav>
        </header>
        {% block content %}
        {% endblock %}
    </body>
</html>

app/templates/change.html
{% extends 'base.html' %}
{% load static %}
{% load form_tags %}
{% block content %}
<h1 style="text-align: center;  padding: 10px;">Изменить впечатление</h1>
    {% render_places_form 'Изменить' data %}
<script src="https://api-maps.yandex.ru/2.1/?apikey={{key_api}}&lang=ru_RU"></script>
<script src="{% static 'js/main.js'%}"></script>
{% endblock %}

app/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% load form_tags %}

{% block content %}
<h1 style="text-align: center;  padding: 10px;">Создать новое впечатление</h1>
{% render_places_form 'Создать' %}
{% if not reviews %}
<h1 style="text-align: center; padding: 10px;">У вас ещё нет воспоминаний</h1>
{% else %}
<h1 style="text-align: center; padding: 10px;">Ваши воспоминания</h1>
<div class="reviews-container d-flex flex-column align-items-center">
    {% for r in reviews %}
        <div class="review-wrapper d-flex">
            <a class="change-button" href="{{r.get_absolute_url}}">Изменить <i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
            <div class="text">
                <h4>{{r.name}}</h4>
                <p>{{r.description}}</p>
            </div>
            <div class="map" id="map{{r.pk}}", longitude="{{r.longitude}}" latitude="{{r.latitude}}">
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}


<script src="https://api-maps.yandex.ru/2.1/?apikey={{key_api}}&lang=ru_RU"></script>
<script src="{% static 'js/main.js'%}"></script>
{% endblock %}

app/templates/startpage.html
{% extends 'base.html' %}
{% block content %}
<div class="greeting-container d-flex justify-content-center align-items-center">
    <div class="window d-flex flex-column justify-content-center align-items-center">
        <h2>Добро пожаловать</h2>
        <p>Сохраняй здесь всё, чтобы ничего не забыть потом</p>
        <a href="{% url 'social:begin' 'vk-oauth2' %}">Зайти с помощью ВКонтакте</a>
    </div>
</div>
{% endblock %}

app/templates/templatetags/form.html
<div class="form-container d-flex justify-content-center">
    <form id="create" class="d-flex flex-column " method="POST" action="{{url}}">
        {% csrf_token %}
        <input type="text" class="p-name" name="name", value="{{data.name}}" maxlength="60", placeholder="Введите текст", required id="id_name">
        <textarea name="description" class="p-descr" placeholder="Расскажите об этом месте"  required id="id_description" cols="40" rows="10">
            {{data.description}}
        </textarea>
        <input type="hidden", value="{{data.latitude}}" name="latitude", step="any", id="id_latitude">
        <input type="hidden", value="{{data.longitude}}" name="longitude", step="any", id="id_longitude">
        <button class="align-self-center" type="submit">{{do}}</button>
    </form>
    <div id="map"></div>
</div>